---
- set_fact:
    docker_arch: "arm64"
  when: ansible_architecture == "aarch64"

- set_fact:
    docker_arch: "amd64"
  when: ansible_architecture == "x86_64"

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - gnupg
    state: latest
    update_cache: true
  become: true

- name: Add signing key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
  become: true
  tags:
    - docker

- name: Add repository to sources
  apt_repository:
    repo: "deb [arch={{ docker_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    update_cache: true
  become: true
  tags:
    - docker

- name: Install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-ce-rootless-extras
      - docker-buildx-plugin
    state: latest
    update_cache: true
  become: true
  tags:
    - docker

- name: Install docker-compose
  pip:
    name: docker-compose

- name: Adding user to docker group
  user:
    name: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: true
