---
- name: Install required packages
  apt:
    name:
      - git
      - vim
      - neovim
      - zsh
      - htop
      - software-properties-common
      - python3-pip
      - python3-venv
      - python3-virtualenv
      - policykit-1
      # - apparmor
      - members
      - avahi-daemon
      - lm-sensors
      - iperf3
      - curl
      - wget
    state: present
  become: true
